name: "Check Pull Request Readiness"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    name: Installing dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache pip
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ./venv/
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          bash .config/venv_setup.sh
      - name: Confirming everything is OK
        run: |
          ls -la venv

  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: [ install-dependencies ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache pip
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ./venv/
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Code Syle
        run: |
          bash .config/run_lint.sh

  unittests:
    name: Unittests
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: [ install-dependencies ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Cache pip
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ./venv/
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Unittests
        run: |
          bash .config/run_tests.sh
